# python3 solve.py SILENT=1
from pwn import *
import re
import string

flag = ""

conn = remote("localhost", 9003)
conn.recv()

charset = string.digits + string.ascii_letters + string.punctuation

while True:
	check = True
	i = 0
	while i < len(charset):
		payload = '*' * (16-len(flag)%16-1) + flag + charset[i] + '*' * (16-len(flag)%16-1)
		conn.sendline(payload)
		res = conn.recvuntil("Input a string to encrypt (input 'q' to quit):\r\n").decode('utf-8')
		ct = re.findall("\r\n([0-9a-f]+)\r\n", res)[0]
		index = int((len(flag)/16 + 1))

		if ct[:32*index] == ct[32*index:2*32*index]:
			flag += charset[i]
			print("Retrieved: " + flag + " (" + payload + ")")
			check = False
			break
		i += 1

	if len(flag) > 0 and flag[-1] == "}":
		conn.close()
		exit("==> Your FLAG: " + flag)

	if check:
		flag = flag[:-1]
    
    
# ╰─# python3 solve.py 
# [+] Opening connection to localhost on port 9003: Done
# Retrieved: u (***************u***************)
# Retrieved: uA (**************uA**************)
# Retrieved: u (***************u***************)
# Retrieved: A (***************A***************)
# Retrieved: A (***************A***************)
# Retrieved: A (***************A***************)
# Retrieved: u (***************u***************)
# Retrieved: ut (**************ut**************)
# Retrieved: utf (*************utf*************)
# Retrieved: utfl (************utfl************)
# Retrieved: utflA (***********utflA***********)
# Retrieved: utfl (************utfl************)
# Retrieved: utfl (************utfl************)
# Retrieved: utfla (***********utfla***********)
# Retrieved: utflag (**********utflag**********)
# Retrieved: utflag{ (*********utflag{*********)
# Retrieved: utflag{3 (********utflag{3********)
# Retrieved: utflag{3A (*******utflag{3A*******)
# Retrieved: utflag{A (********utflag{A********)
# Retrieved: utflag{3 (********utflag{3********)
# Retrieved: utflag{A (********utflag{A********)
# Retrieved: utflag{A (********utflag{A********)
# Retrieved: utflag{3 (********utflag{3********)
# Retrieved: utflag{3 (********utflag{3********)
# Retrieved: utflag{3A (*******utflag{3A*******)
# Retrieved: utflag{3A (*******utflag{3A*******)
# Retrieved: utflag{3c (*******utflag{3c*******)
# Retrieved: utflag{3A (*******utflag{3A*******)
# Retrieved: utflag{3c (*******utflag{3c*******)
# Retrieved: utflag{3cb (******utflag{3cb******)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cb_ (*****utflag{3cb_*****)
# Retrieved: utflag{3cb_w (****utflag{3cb_w****)
# Retrieved: utflag{3cb_wA (***utflag{3cb_wA***)
# Retrieved: utflag{3cb_wA (***utflag{3cb_wA***)
# Retrieved: utflag{3cb_w1 (***utflag{3cb_w1***)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w1A (**utflag{3cb_w1A**)
# Retrieved: utflag{3cb_w1 (***utflag{3cb_w1***)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w1A (**utflag{3cb_w1A**)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w17A (*utflag{3cb_w17A*)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17A (*utflag{3cb_w17A*)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17h_ (utflag{3cb_w17h_)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w1 (***utflag{3cb_w1***)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w17A (*utflag{3cb_w17A*)
# Retrieved: utflag{3cb_ (*****utflag{3cb_*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cA (******utflag{3cA******)
# Retrieved: utflag{3cb (******utflag{3cb******)
# Retrieved: utflag{3cA (******utflag{3cA******)
# Retrieved: utflag{3cA (******utflag{3cA******)
# Retrieved: utflag{3cb (******utflag{3cb******)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cb (******utflag{3cb******)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cA (******utflag{3cA******)
# Retrieved: utflag{3cb (******utflag{3cb******)
# Retrieved: utflag{3cbA (*****utflag{3cbA*****)
# Retrieved: utflag{3cb_ (*****utflag{3cb_*****)
# Retrieved: utflag{3cb_w (****utflag{3cb_w****)
# Retrieved: utflag{3cb_w1 (***utflag{3cb_w1***)
# Retrieved: utflag{3cb_w1A (**utflag{3cb_w1A**)
# Retrieved: utflag{3cb_w1A (**utflag{3cb_w1A**)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w17A (*utflag{3cb_w17A*)
# Retrieved: utflag{3cb_w1A (**utflag{3cb_w1A**)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w (****utflag{3cb_w****)
# Retrieved: utflag{3cb_w1 (***utflag{3cb_w1***)
# Retrieved: utflag{3cb_wA (***utflag{3cb_wA***)
# Retrieved: utflag{3cb_wA (***utflag{3cb_wA***)
# Retrieved: utflag{3cb_wA (***utflag{3cb_wA***)
# Retrieved: utflag{3cb_wA (***utflag{3cb_wA***)
# Retrieved: utflag{3cb_w1 (***utflag{3cb_w1***)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17A (*utflag{3cb_w17A*)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w1A (**utflag{3cb_w1A**)
# Retrieved: utflag{3cb_w1A (**utflag{3cb_w1A**)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17h_ (utflag{3cb_w17h_)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17A (*utflag{3cb_w17A*)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17 (**utflag{3cb_w17**)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17hA (utflag{3cb_w17hA)
# Retrieved: utflag{3cb_w17h (*utflag{3cb_w17h*)
# Retrieved: utflag{3cb_w17h_ (utflag{3cb_w17h_)
# Retrieved: utflag{3cb_w17h_r (***************utflag{3cb_w17h_r***************)
# Retrieved: utflag{3cb_w17h_rA (**************utflag{3cb_w17h_rA**************)
# Retrieved: utflag{3cb_w17h_rA (**************utflag{3cb_w17h_rA**************)
# Retrieved: utflag{3cb_w17h_r4 (**************utflag{3cb_w17h_r4**************)
# Retrieved: utflag{3cb_w17h_r4n (*************utflag{3cb_w17h_r4n*************)
# Retrieved: utflag{3cb_w17h_r4nd (************utflag{3cb_w17h_r4nd************)
# Retrieved: utflag{3cb_w17h_r4nd (************utflag{3cb_w17h_r4nd************)
# Retrieved: utflag{3cb_w17h_r4nd0 (***********utflag{3cb_w17h_r4nd0***********)
# Retrieved: utflag{3cb_w17h_r4nd0A (**********utflag{3cb_w17h_r4nd0A**********)
# Retrieved: utflag{3cb_w17h_r4nd0m (**********utflag{3cb_w17h_r4nd0m**********)
# Retrieved: utflag{3cb_w17h_r4nd0mA (*********utflag{3cb_w17h_r4nd0mA*********)
# Retrieved: utflag{3cb_w17h_r4nd0mA (*********utflag{3cb_w17h_r4nd0mA*********)
# Retrieved: utflag{3cb_w17h_r4nd0mA (*********utflag{3cb_w17h_r4nd0mA*********)
# Retrieved: utflag{3cb_w17h_r4nd0m (**********utflag{3cb_w17h_r4nd0m**********)
# Retrieved: utflag{3cb_w17h_r4nd0m_ (*********utflag{3cb_w17h_r4nd0m_*********)
# Retrieved: utflag{3cb_w17h_r4nd0m_p (********utflag{3cb_w17h_r4nd0m_p********)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr (*******utflag{3cb_w17h_r4nd0m_pr*******)
# Retrieved: utflag{3cb_w17h_r4nd0m_prA (******utflag{3cb_w17h_r4nd0m_prA******)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3 (******utflag{3cb_w17h_r4nd0m_pr3******)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f (*****utflag{3cb_w17h_r4nd0m_pr3f*****)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1 (****utflag{3cb_w17h_r4nd0m_pr3f1****)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1x (***utflag{3cb_w17h_r4nd0m_pr3f1x***)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1A (***utflag{3cb_w17h_r4nd0m_pr3f1A***)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1 (****utflag{3cb_w17h_r4nd0m_pr3f1****)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1x (***utflag{3cb_w17h_r4nd0m_pr3f1x***)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1 (****utflag{3cb_w17h_r4nd0m_pr3f1****)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1x (***utflag{3cb_w17h_r4nd0m_pr3f1x***)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1xA (**utflag{3cb_w17h_r4nd0m_pr3f1xA**)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1x (***utflag{3cb_w17h_r4nd0m_pr3f1x***)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3fA (****utflag{3cb_w17h_r4nd0m_pr3fA****)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3fA (****utflag{3cb_w17h_r4nd0m_pr3fA****)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1 (****utflag{3cb_w17h_r4nd0m_pr3f1****)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1x (***utflag{3cb_w17h_r4nd0m_pr3f1x***)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1xA (**utflag{3cb_w17h_r4nd0m_pr3f1xA**)
# Retrieved: utflag{3cb_w17h_r4nd0m_pr3f1x} (**utflag{3cb_w17h_r4nd0m_pr3f1x}**)
# [*] Closed connection to localhost port 9003
# ==> Your FLAG: utflag{3cb_w17h_r4nd0m_pr3f1x}
